### ISSUE TITLE
Moving on: minor improvements (no new data needed)

### ISSUE THREAD

**Issue by ortiztudela** [ortiztud/ecos#1]
Here is a list of the suggestions that came out of the presentation:

# Spatial frequency info.
I think at some point you made something in this line. I am not sure of how this information can be presented. Power of each band of frequency?

# Frequency filtered images.
We can provide low- and high-pass filtered versions of all the images and/or we can provide a plug & play function that filters the images when given a specific range.

# Black and white images.
Same as below.

# Descriptive features
A table that summarizes all the info for easier handling. Maybe including high order features such as "natural" (e.g., beach, mountain) vs "artificial" (e.g., road, stadium).

**Comment by gonzalezgarcia** [comment]
General comment: the goal here is to show that scenes/objects don't differ in low level features, right? If we are able to do so, and then show that objects/scenes are clustered based on semantic categories I think we have a strong point.
If we can show that scenes/objects don't differ in low level features, then maybe don't have to provide low- and/or high-pass filtered versions of the images? Same for B&W.
The idea of the descriptive features table sounds good!

**Comment by ortiztudela** [comment]
I like that way of framing it. I'll get to the descriptive table.

**Comment by ortiztudela** [comment]
I am working on the table annotating the scenes and objects. So far I’ve put in the initial label that we gave to the scenes (e.g., beach, dog, etc) and natural vs artificial, any idea of what else could be interesting?

If we finally do the naming task (i.e., type the name of this object), we could put the most common word there as well. What do you think?

**Comment by gonzalezgarcia** [comment]
what's natural vs. artificial?
maybe we can also add the mean score of relatedness to each scene (this would be only for the obejcts table)

**Comment by ortiztudela** [comment]
Beach - Natural
Road - Artificial
Coyote - Natural
Road sign - Artificial

I’ll get to the mean relatedness thing.

**Comment by gonzalezgarcia** [comment]
so natural vs manmade?

**Comment by ortiztudela** [comment]
Yep

**Comment by ortiztudela** [comment]
We have decided to use low-level (color and saliency), mid-level (animacy) and high-level (category) RDMs to explain the responses RDMs. This information will also be included in the descriptive table and that should provide all the information needed in that respect. 

Closing this up.
