### ISSUE TITLE
Moving on: major improvements (new data needed)

### ISSUE THREAD

**Issue by ortiztudela** [ortiztud/ecos#2]
These are the two main ideas that came out in terms of new data. They are not necessarily two different things rather two different ways of addressing the same issue. Namely, to what extent the pictures that we chose for the objects are a good candidate of the semantic label that we intended. It is true that, our focus is on the relation between objects and scenes (not about objects themselves) but if you think about a priming-like paradigm in which scenes and objects will be presented sequentially, then this issue becomes specially relevant (more so if the order is scene > object).

# "Prototypicality" of the items.
We have thought about this at some point. Presenting the objects and asking them "how prototypical is this tiger of tigerness".

# "Recognizability of the objects"
Some people brought up the issue that, when taken in isolation, some of the objects might be miscategorized (as indeed happened with the "coyote/wolf"). The suggestion was to ask people to verbally identify the objects. However this comes at the huge cost of coding the responses.

A solution to that problem is to provide a measure of agreement between judges for every object. We can select the "most agreed upon" label as the preferred one, but also provide a measure of dispersion in naming the objects. I can see how that could be useful to select "highly consistently named objects" vs "ambiguous" objects.

**Comment by gonzalezgarcia** [comment]
I think these two could be combined right?

We could first show an image and offer different possibilities (of course, this is also costly because we have to come up with all the possibilities), make participants pick one, and then rate how prototypical that object is regarding the label they picked.

**Comment by gonzalezgarcia** [comment]
In any case, programming should be relatively straightforward and I think I could do it more or less quickly

**Comment by ortiztudela** [comment]
Now that I see my past again I realize that there was a key thing missing in the second point: "we can ask people to type down the name of the object". Then we can select the agreement on that. Potentially we could lets say, take the first 3 letters (to get rid of plurals, typos and so).

**Comment by gonzalezgarcia** [comment]
Ok. I think this should be quite straightforward to do...

**Comment by ortiztudela** [comment]
Do you think this would be easy to do in JavaScript? Could you upload one of your scripts so I can look at them (I’ve never seen an experiment on JS, so I’m very curious).

**Comment by ortiztudela** [comment]
We decided not to include any new data due to the re-framing of the paper.

Cierro al salir.
